insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-08', 'Kaio', 'Retirada da pasta', '800x600', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-13', 'Celio', 'Entupida', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-13', 'Vagner', 'encontrada rasgada no cavalete', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-14', 'Diego/Leonardo', 'Entupida de verniz', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-14', 'Pedro', 'Retirada da pasta', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-16', 'Diego', 'Imprimindo', '1900x1000', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Ricardo', 'achou rasgada', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Celio', 's/ condição de uso (cheia de pingo de emulsão)', '3000x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Celio', 'Verniz seco mal lavada', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Diego', 'Imprimindo', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Celio', 'retirada da emulsão (desplaque)', '3000x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-17', 'Vagner', 'encontrada rasgada no cavalete', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-20', 'Kaio', 'retirada da pasta', '810x740', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-21', 'vagner', 'retirada da estufa (aquec. Excessivo)', '810x740', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-22', 'Celio', 'bateu na outra', '800x750', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-22', 'Kaio', 'retirada da estufa', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-22', 'Kaio', 'retirada da estufa', '910x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-22', 'Vagner', 'encontrada rasgada no cavalete', '910x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-22', 'Vagner', 'retirada da fita', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-23', 'Marcela', 'achou rasgada', '800x750', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-23', 'Pedro', 'Retirada da pasta (wap)', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-24', 'Igor', 'Ordem do Fernando Entupida', '3000x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-24', 'Kaio', 'retirada da pasta', '810x750', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-24', 'Kaio', 'Retirada da pasta (wap)', '910x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-27', 'Vagner', 'fazendo a limpeza (retirada fita)', '710x600', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-28', 'João', 'Imprimindo', '1200x1000', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-28', 'Kaio', 'Retirada da estufa', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-29', 'João', 'Imprimindo', '3000x1000', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-29', 'Celio', 'Tela com furo demais fio 150', '', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-30', 'Rotativa', 'rasgou na operação', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-30', 'Kaio', 'rasgou na retirada emulsão', '910x710', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-30', 'Kaio', 'rasgou na retirada emulsão', '910x710', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-07-30', 'Vagner', 'rasgou na retirada da estufa', '900x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-03', 'Igor', 'Rasgou na mão dele', '800x750', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-03', 'Celio', 'Entupida cheia de verniz seco', '3000x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-04', 'Vagner', 'encontrada rasgada no cavalete', '800x750', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-06', 'Celio', 'verniz seco tela entupida', '1040x940', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-10', 'Kaio', 'rasgou na retirada da pasta', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-10', 'Kaio', 'rasgou na retirada da emulsão', '770x640', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-12', 'Kaio', 'bateu uma na outra', '900x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-13', 'Marcela', 'Imprimindo', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-17', 'João', 'entupida reprovou', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-17', 'Leonardo', 'entupida reprovou', '1900x1101', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-17', 'Kaio', 'retirada da emulsão (desplaque)', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-18', 'Kaio', 'retirada da emulsão (desplaque)', '900x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-17', 'Kaio', 'retirada da pasta (wap)', '560x460', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-18', 'Vitoria', 'Imprimindo', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-18', 'Rapaz gráfica', 'bateu uma na outra', '800x600', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-20', 'Vagner', 'retirada da estufa', '600x700', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-20', 'Pedro', 'retirada da emulsão (desplaque)', '750x800', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-21', 'Kaio', 'retirada da estufa', '700x900', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-21', 'Vagner', 'retirada da emulsão (desplaque)', '700x600', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-24', 'Celio', 'não saiu a emulsão', '3000x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-25', 'Sidnei', 'na maquina montando', '300x1260', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-25', 'Diego', 'Imprimindo', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-25', 'Celio', 'bateu o tubo', '2000x1000', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-05-26', 'Cleber', 'Imprimindo', '940x720', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-26', 'Celio', 'tale entupida', '1900x1100', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-27', 'Vagner', 'retirada da emulsão (wap)', '840x670', '');
insert into telas_rasgadas (data, operador, motivo, tamanho, observacao) values ('2026-08-27', 'Kaio', 'retirada da emulsão (wap)', '700x600', '');
