insert into operadores (nome) values ('Alisson') on conflict (nome) do nothing;
insert into operadores (nome) values ('Alyson') on conflict (nome) do nothing;
insert into operadores (nome) values ('Ana') on conflict (nome) do nothing;
insert into operadores (nome) values ('Carlos') on conflict (nome) do nothing;
insert into operadores (nome) values ('Celio') on conflict (nome) do nothing;
insert into operadores (nome) values ('Cleber') on conflict (nome) do nothing;
insert into operadores (nome) values ('Célio') on conflict (nome) do nothing;
insert into operadores (nome) values ('Daniel') on conflict (nome) do nothing;
insert into operadores (nome) values ('Diego') on conflict (nome) do nothing;
insert into operadores (nome) values ('Diego/Leonardo') on conflict (nome) do nothing;
insert into operadores (nome) values ('Eliana R.') on conflict (nome) do nothing;
insert into operadores (nome) values ('Eliane C.') on conflict (nome) do nothing;
insert into operadores (nome) values ('Eliane Couto') on conflict (nome) do nothing;
insert into operadores (nome) values ('Eliane R.') on conflict (nome) do nothing;
insert into operadores (nome) values ('Felipe') on conflict (nome) do nothing;
insert into operadores (nome) values ('Igor') on conflict (nome) do nothing;
insert into operadores (nome) values ('Igor / Celio') on conflict (nome) do nothing;
insert into operadores (nome) values ('João') on conflict (nome) do nothing;
insert into operadores (nome) values ('Jéssica') on conflict (nome) do nothing;
insert into operadores (nome) values ('Kaio') on conflict (nome) do nothing;
insert into operadores (nome) values ('Karen') on conflict (nome) do nothing;
insert into operadores (nome) values ('Kevyn') on conflict (nome) do nothing;
insert into operadores (nome) values ('Leonardo') on conflict (nome) do nothing;
insert into operadores (nome) values ('Maisa') on conflict (nome) do nothing;
insert into operadores (nome) values ('Marcela') on conflict (nome) do nothing;
insert into operadores (nome) values ('Maísa') on conflict (nome) do nothing;
insert into operadores (nome) values ('Otávio') on conflict (nome) do nothing;
insert into operadores (nome) values ('Paulo') on conflict (nome) do nothing;
insert into operadores (nome) values ('Pedro') on conflict (nome) do nothing;
insert into operadores (nome) values ('Rapaz gráfica') on conflict (nome) do nothing;
insert into operadores (nome) values ('Ricardo') on conflict (nome) do nothing;
insert into operadores (nome) values ('Rotativa') on conflict (nome) do nothing;
insert into operadores (nome) values ('Rotativa 4') on conflict (nome) do nothing;
insert into operadores (nome) values ('Sidnei') on conflict (nome) do nothing;
insert into operadores (nome) values ('Simone') on conflict (nome) do nothing;
insert into operadores (nome) values ('Sirlene') on conflict (nome) do nothing;
insert into operadores (nome) values ('Thais') on conflict (nome) do nothing;
insert into operadores (nome) values ('Tião') on conflict (nome) do nothing;
insert into operadores (nome) values ('Vagner') on conflict (nome) do nothing;
insert into operadores (nome) values ('Victor') on conflict (nome) do nothing;
insert into operadores (nome) values ('Vinicius') on conflict (nome) do nothing;
insert into operadores (nome) values ('Vitoria') on conflict (nome) do nothing;
insert into operadores (nome) values ('vagner') on conflict (nome) do nothing;
insert into motivos (nome) values ('Achou Rasgada') on conflict (nome) do nothing;
insert into motivos (nome) values ('Achou Rasgada no cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('Achou rasgada') on conflict (nome) do nothing;
insert into motivos (nome) values ('Achou rasgada cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('Bateu na outra') on conflict (nome) do nothing;
insert into motivos (nome) values ('Bateu no carrinho') on conflict (nome) do nothing;
insert into motivos (nome) values ('Caiu na mesa') on conflict (nome) do nothing;
insert into motivos (nome) values ('Derrubou') on conflict (nome) do nothing;
insert into motivos (nome) values ('Derrubou alumínio na tela') on conflict (nome) do nothing;
insert into motivos (nome) values ('Descolou') on conflict (nome) do nothing;
insert into motivos (nome) values ('Descolou no solvente') on conflict (nome) do nothing;
insert into motivos (nome) values ('Desplacando') on conflict (nome) do nothing;
insert into motivos (nome) values ('Desplaque') on conflict (nome) do nothing;
insert into motivos (nome) values ('Encontrada rasgada') on conflict (nome) do nothing;
insert into motivos (nome) values ('Entupida') on conflict (nome) do nothing;
insert into motivos (nome) values ('Entupida cheia de verniz seco') on conflict (nome) do nothing;
insert into motivos (nome) values ('Entupida de verniz') on conflict (nome) do nothing;
insert into motivos (nome) values ('Espátula') on conflict (nome) do nothing;
insert into motivos (nome) values ('Estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('Furou no meio') on conflict (nome) do nothing;
insert into motivos (nome) values ('Imprimindo') on conflict (nome) do nothing;
insert into motivos (nome) values ('Krmai (Entupida tinta com problema)') on conflict (nome) do nothing;
insert into motivos (nome) values ('Lavando tirando pasta') on conflict (nome) do nothing;
insert into motivos (nome) values ('Limpando') on conflict (nome) do nothing;
insert into motivos (nome) values ('Limpando (jato wap)') on conflict (nome) do nothing;
insert into motivos (nome) values ('Manuseio') on conflict (nome) do nothing;
insert into motivos (nome) values ('Montando') on conflict (nome) do nothing;
insert into motivos (nome) values ('Montando na maquina') on conflict (nome) do nothing;
insert into motivos (nome) values ('Montando na máquina') on conflict (nome) do nothing;
insert into motivos (nome) values ('Muito furo') on conflict (nome) do nothing;
insert into motivos (nome) values ('Muito velha') on conflict (nome) do nothing;
insert into motivos (nome) values ('Na produção') on conflict (nome) do nothing;
insert into motivos (nome) values ('Ordem do Fernando Entupida') on conflict (nome) do nothing;
insert into motivos (nome) values ('Pasta Pregan') on conflict (nome) do nothing;
insert into motivos (nome) values ('Pasta pregan') on conflict (nome) do nothing;
insert into motivos (nome) values ('Processo de secagem (estufa)') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasagada no cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasgada no cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasgou na estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasgou na mão dele') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasgou no processo') on conflict (nome) do nothing;
insert into motivos (nome) values ('Rasgou sozinha') on conflict (nome) do nothing;
insert into motivos (nome) values ('Retirada da estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('Retirada da pasta') on conflict (nome) do nothing;
insert into motivos (nome) values ('Retirada da pasta (wap)') on conflict (nome) do nothing;
insert into motivos (nome) values ('Retirada estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('Retirando pasta alcalina') on conflict (nome) do nothing;
insert into motivos (nome) values ('Revisando') on conflict (nome) do nothing;
insert into motivos (nome) values ('S/ condição de uso (estufa)') on conflict (nome) do nothing;
insert into motivos (nome) values ('S/ condição de uso muito velha s/ pressao') on conflict (nome) do nothing;
insert into motivos (nome) values ('Sem condição de uso') on conflict (nome) do nothing;
insert into motivos (nome) values ('Sem tensão') on conflict (nome) do nothing;
insert into motivos (nome) values ('Tela com furo demais fio 150') on conflict (nome) do nothing;
insert into motivos (nome) values ('Tirando a fita') on conflict (nome) do nothing;
insert into motivos (nome) values ('Tirando a tinta') on conflict (nome) do nothing;
insert into motivos (nome) values ('Toda entupida') on conflict (nome) do nothing;
insert into motivos (nome) values ('Veio com rasgo grande') on conflict (nome) do nothing;
insert into motivos (nome) values ('Ventilador caiu na tela') on conflict (nome) do nothing;
insert into motivos (nome) values ('Verniz seco') on conflict (nome) do nothing;
insert into motivos (nome) values ('Verniz seco mal lavada') on conflict (nome) do nothing;
insert into motivos (nome) values ('achada rasgada no calete') on conflict (nome) do nothing;
insert into motivos (nome) values ('achou rasgada') on conflict (nome) do nothing;
insert into motivos (nome) values ('achou rasgada no cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('bateu ao separar') on conflict (nome) do nothing;
insert into motivos (nome) values ('bateu em outra') on conflict (nome) do nothing;
insert into motivos (nome) values ('bateu na outra') on conflict (nome) do nothing;
insert into motivos (nome) values ('bateu o tubo') on conflict (nome) do nothing;
insert into motivos (nome) values ('bateu uma na outra') on conflict (nome) do nothing;
insert into motivos (nome) values ('desplacando') on conflict (nome) do nothing;
insert into motivos (nome) values ('desplaque') on conflict (nome) do nothing;
insert into motivos (nome) values ('encontrada rasgada no cavalete') on conflict (nome) do nothing;
insert into motivos (nome) values ('entupida reprovou') on conflict (nome) do nothing;
insert into motivos (nome) values ('estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('fazendo a limpeza (retirada fita)') on conflict (nome) do nothing;
insert into motivos (nome) values ('limpeza produção') on conflict (nome) do nothing;
insert into motivos (nome) values ('na maquina montando') on conflict (nome) do nothing;
insert into motivos (nome) values ('não saiu a emulsão') on conflict (nome) do nothing;
insert into motivos (nome) values ('queda da tela') on conflict (nome) do nothing;
insert into motivos (nome) values ('rasgou na operação') on conflict (nome) do nothing;
insert into motivos (nome) values ('rasgou na retirada da emulsão') on conflict (nome) do nothing;
insert into motivos (nome) values ('rasgou na retirada da estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('rasgou na retirada da pasta') on conflict (nome) do nothing;
insert into motivos (nome) values ('rasgou na retirada emulsão') on conflict (nome) do nothing;
insert into motivos (nome) values ('reprovou processo, tensão velha') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da emulsão (desplaque)') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da emulsão (wap)') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da estufa') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da estufa (aquec. Excessivo)') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da fita') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da pasta') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada da pasta (wap)') on conflict (nome) do nothing;
insert into motivos (nome) values ('retirada fita (desplaque)') on conflict (nome) do nothing;
insert into motivos (nome) values ('s/ condição de uso (cheia de pingo de emulsão)') on conflict (nome) do nothing;
insert into motivos (nome) values ('sem condição de uso') on conflict (nome) do nothing;
insert into motivos (nome) values ('tale entupida') on conflict (nome) do nothing;
insert into motivos (nome) values ('tela entupida') on conflict (nome) do nothing;
insert into motivos (nome) values ('tela rasgada') on conflict (nome) do nothing;
insert into motivos (nome) values ('verniz seco tela entupida') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('-') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.000x800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.009x1.009') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.030x1.100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.030x940') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.040x930') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.100x1.100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.200x100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.200x800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.260x1.900') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.260x3.000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.260x860') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.270x870') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.300x1.900') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.300x900') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.400x1.000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.400x1.001') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.900x1.000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.900x1.100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1.900x1x100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1000X800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1000x1119') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1000x3000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1000x800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1030/940') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1030x940') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1040x930') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1040x940') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1090x1090') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1100x1100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1170x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1200x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1200x800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1270x870') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1280x870') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1300x900') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1400x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1410x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1850x1350') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1900X1100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1900x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1900x1010') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1900x1100') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('1900x1101') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('2.000x1.850') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('2.500x1.000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('2000x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3.000x1.000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3.000x1.270') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3.000x980') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3000x1000') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3000x1260') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('3000x1270') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('300x1260') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('340x720') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('410x710') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('540x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('560x460') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('600x700') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('700x600') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('700x900') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('710x600') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('730x640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('750x800') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('760x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('770x640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('770x660') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('770x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('800x600') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('800x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('800x770') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('810x600') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('810x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('810x720') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('810x740') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('810x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('840X640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('840x640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('840x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('840x740') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('840x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('8420x640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('870x600') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('870x640') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('900x700') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('910x695') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('910x700') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('910x710') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('910x720') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('940x670') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('940x720') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('940x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('950x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('960x740') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('960x750') on conflict (nome) do nothing;
insert into tamanhos_tela (nome) values ('970x670') on conflict (nome) do nothing;
